kind: Deployment
apiVersion: apps/v1
metadata:
  name: $APP_NAME
  namespace: develop
  labels:
    app: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
#      volumes.name只能是小写
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-configmap
          configMap:
            name: $APP_NAME-config
            defaultMode: 420
      containers:
        - name: container-$BUILD_NUMBER
          image: $REMOTO_REGISTRY/$NAMESPACE/$APP_NAME:$VERSION.$BUILD_NUMBER
#          ports.name不能超过15个字符
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
#          resources:
#            limits:
#              cpu: 300m
#              memory: 500Mi
#            requests:
#              cpu: 300m
#              memory: 500Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-configmap
              readOnly: true
#              挂载的目录为/config时，java -jar不用指定--spring.config.location=classpath:/application.yml,/config/，--logging.config=/config/logback-spring.xml
              mountPath: /config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

---
kind: Service
apiVersion: v1
metadata:
  name: $APP_NAME-svc
  namespace: develop
  labels:
    app: $APP_NAME-svc
spec:
  ports:
    - name: http-$APP_NAME-svc
      protocol: TCP
      port: 80
      targetPort: 80
#      不指定nodePort将随机分配
#      nodePort: 32121
  selector:
    app: $APP_NAME
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
