kind: Deployment
apiVersion: apps/v1
metadata:
  name: $APP_NAME
  namespace: develop
  labels:
    app: pipeline-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-configMap
          configMap:
            name: pipeline-web-config
            defaultMode: 420
      containers:
        - name: container-$BUILD_NUMBER
          image: $REMOTO_REGISTRY/$NAMESPACE/$APP_NAME:$VERSION.$BUILD_NUMBER
          ports:
            - name: http-pipeline
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-configMap
              readOnly: true
              mountPath: /config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

---
kind: Service
apiVersion: v1
metadata:
  name: pipeline-web-svc
  namespace: develop
  labels:
    app: pipeline-web-svc
spec:
  ports:
    - name: http-pipeline-web-svc
      protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 32121
  selector:
    app: pipeline-web
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
